version: "3.9"

services:
  db:
    image: postgres:15
    container_name: photoshare_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: photoshare_app
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
