[pytest]
# Автоматичний режим для асинхронних тестів
asyncio_mode = auto

# Шлях до тестів
testpaths = tests

# Додаємо корінь проєкту в sys.path
pythonpath = .

# Автоматичні параметри запуску
# --cov=app → рахує покриття по всій директорії app/
# --cov-report=term-missing → показує які рядки не покриті
# --cov-fail-under=90 → якщо покриття <90%, тести падають
; addopts = --cov=app --cov-report=term-missing --cov-fail-under=90

# тимчасово без перевірки покриття
addopts = --cov=app --cov-report=term-missing

# Прибираємо попередження
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::RuntimeWarning
