"""cascade delete

Revision ID: 273db80ac716
Revises: 67af0c2ce6e3
Create Date: 2026-08-23 16:58:05.625268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273db80ac716'
down_revision: Union[str, Sequence[str], None] = '67af0c2ce6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_photo_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'photos', ['photo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('photo_transforms_photo_id_fkey'), 'photo_transforms', type_='foreignkey')
    op.create_foreign_key(None, 'photo_transforms', 'photos', ['photo_id'], ['id'], ondelete='CASCADE')
    op.alter_column('photos', 'public_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'public_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'photo_transforms', type_='foreignkey')
    op.create_foreign_key(op.f('photo_transforms_photo_id_fkey'), 'photo_transforms', 'photos', ['photo_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_photo_id_fkey'), 'comments', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###
