"""add public_id to Photo and create PhotoTransform table

Revision ID: 67af0c2ce6e3
Revises: ef01a44b777b
Create Date: 2026-08-22 15:30:53.795096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67af0c2ce6e3'
down_revision: Union[str, Sequence[str], None] = 'ef01a44b777b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_transforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('transformed_url', sa.String(), nullable=False),
    sa.Column('qr_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_transforms_id'), 'photo_transforms', ['id'], unique=False)
    op.add_column('photos', sa.Column('public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'public_id')
    op.drop_index(op.f('ix_photo_transforms_id'), table_name='photo_transforms')
    op.drop_table('photo_transforms')
    # ### end Alembic commands ###
